### ISSUE TITLE
图形界面可kill掉

### ISSUE THREAD

**Issue by ivyswen** [qianyingshuo/resign-forever#2]
刚刚在centos5上测试,通过kvm登录图形界面,打开终端,top,ps找到这个进程就能杀掉.

**Comment by qianyingshuo** [comment]
我已经修改了脚本，现在能够写入tty设备了，不过我是在Fedora 22上测试，你可以试一下。 

感谢反馈

**Comment by qianyingshuo** [comment]
尝试了写入tty设备当中，但是普通用户没有写入其他tty设备的权限，也就是如果用kvm登陆图形界面确实是杀掉该进程的好办法。
