### ISSUE TITLE
新脚本还不如旧脚本好用

### ISSUE THREAD

**Issue by ivyswen** [qianyingshuo/resign-forever#3]
普通用户下执行新脚本，报“./haha.sh: line 29: /dev/tty34: 权限不够”然后直接CTRL+C就可以结束了，都不用KVM。

用root用户是可以达到预期效果的。

close这个issues吧

**Comment by qianyingshuo** [comment]
是的，新的脚本会向tty写入，普通用户没有向tty写入的权限，所以会有报权限不足的错。至于用CTRL+C能够结束，是因为你没有后台执行。 这一点之前的脚本也是一样的。
